TheThrift/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TheThrift.Contracts;
using TheThrift.Data;
using TheThrift.Models;

namespace TheThrift.Controllers
{
    public class ClientsController : Controller
    {
        private readonly IClientRepository _repo;
        private readonly IMapper _mapper;

        public ClientsController(IClientRepository repo, IMapper mapper)
        {
            _repo = repo;
            _mapper = mapper;
        }
        // GET: CustomersController
        public ActionResult Index()
        {
            var customers = _repo.FindAll().ToList();
            var collection = _mapper.Map<List<Client>, List<ClientVM>>(customers);
                //.OrderBy(b => b.DateRegistered);
            return View(collection);
        }

        // GET: CustomersController/Details/5
        public ActionResult Details(int id)
        {
            if (!_repo.isExist(id))
            {
                return NotFound();
            }
            var customers = _repo.FindById(id);
            var collections = _mapper.Map<ClientVM>(customers);
            return View(collections);
        }

        // GET: CustomersController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CustomersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ClientVM collection)
        {
            try
            {
                //TODO: Add insert logic here

                if (!ModelState.IsValid)
                {
                    return View(collection);
                }
                var customers = _mapper.Map<Client>(collection);
                customers.DateCreated = DateTime.Now;

                var isSuccess = _repo.Create(customers);
                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something Went Wrong...");
                    return View(collection);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something Went Wrong...");
                return View(collection);
            }
        }

        // GET: CustomersController/Edit/5
        public ActionResult Edit(int id)
        {
            if (!_repo.isExist(id))
            {
                return NotFound();
            }
            var customers = _repo.FindById(id);
            var collection = _mapper.Map<ClientVM>(customers);
            return View(collection);
        }

        // POST: CustomersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ClientVM collection)
        {
            try
            {
                //TODO: Added some update logic here
                if (!ModelState.IsValid)
                {
                    return View(collection);
                }
                var customer = _mapper.Map<Client>(collection);
                var isSuccess = _repo.Update(customer);

                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something Went Wrong...");
                    return View(collection);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something Went Wrong...");
                return View(collection);
            }
        }

        // GET: CustomersController/Delete/5
        public ActionResult Delete(int id)
        {
            //checking if there is any record for that particular Id
            var custoers = _repo.FindById(id);
            if (custoers == null)
            {
                return NotFound();
            }
            var isSuccess = _repo.Delete(custoers);
            if (!isSuccess)
            {
                return View();
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: CustomersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, ClientVM collection)
        {
            try
            {
                //TODO: Add delete logic here 
                var expenses = _repo.FindById(id);
                if (expenses == null)
                {
                    return NotFound();
                }
                var isSuccess = _repo.Delete(expenses);
                if (!isSuccess)
                {
                    return BadRequest();
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(collection);
            }
        }
    }
}

TheThrift/Controllers/ExpensesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TheThrift.Contracts;
using TheThrift.Data;
using TheThrift.Models;

namespace TheThrift.Controllers
{
    public class ExpensesController : Controller
    {
        private readonly IExpensesRepository _repo;
        private readonly IMapper _mapper;

        public ExpensesController(IExpensesRepository repo, IMapper mapper)
        {
            _repo = repo;
            _mapper = mapper;
        }
        // GET: ExpensesController
        public ActionResult Index()
        {
            var expenses = _repo.FindAll().ToList();
            var model = _mapper.Map<List<Expenses>, List<ExpensesVM>>(expenses);
            return View(model);
        }

        // GET: ExpensesController/Details/5
        public ActionResult Details(int id)
        {
            if (!_repo.isExist(id))
            {
                return NotFound();
            }
            var expenses = _repo.FindById(id);
            var collection = _mapper.Map<ExpensesVM>(expenses);
            return View(collection);
        }

        // GET: ExpensesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ExpensesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ExpensesVM collection)
        {
            try
            {
                //TODO: Add insert logic here
                if (!ModelState.IsValid)
                {
                    return View(collection);
                }
                var expenses = _mapper.Map<Expenses>(collection);
                expenses.DateCreated = DateTime.Now;

                var isSuccess = _repo.Create(expenses);
                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something Went Wrong...");
                    return View(collection);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something Went Wrong...");
                return View(collection);
            }
        }

        // GET: ExpensesController/Edit/5
        public ActionResult Edit(int id)
        {
            if (!_repo.isExist(id))
            {
                return NotFound();
            }
            var expenses = _repo.FindById(id);
            var collection = _mapper.Map<ExpensesVM>(expenses);
            return View(collection);
        }

        // POST: ExpensesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ExpensesVM collection)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(collection);
                }
                var expenses = _mapper.Map<Expenses>(collection);
                var isSuccess = _repo.Update(expenses);
                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something Went Wrong...");
                    return View(collection);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something Went Wrong...");
                return View(collection);
            }
        }

        // GET: ExpensesController/Delete/5
        public ActionResult Delete(int id)
        {
            //checking if there is any record for that particular Id
            var expenses = _repo.FindById(id);
            if (expenses == null)
            {
                return NotFound();
            }
            var isSuccess = _repo.Delete(expenses);
            if (!isSuccess)
            {
                return View();
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: ExpensesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, ExpensesVM collection)
        {
            try
            {
                //TODO: Add delete logic here 
                var expenses = _repo.FindById(id);
                if (expenses == null)
                {
                    return NotFound();
                }
                var isSuccess = _repo.Delete(expenses);
                if (!isSuccess)
                {
                    return BadRequest();
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(collection);
            }
        }
    }
}

TheThrift/Controllers/SalaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using TheThrift.Contracts;
using TheThrift.Data;
using TheThrift.Models;

namespace TheThrift.Controllers
{
    public class SalaryController : Controller
    {
        private readonly ISalaryRepository _repo;
        private readonly IMapper _mapper;

        public SalaryController(ISalaryRepository repo, IMapper mapper)
        {
            _repo = repo;
            _mapper = mapper;
        }

        // GET: SalaryController
        public ActionResult Index()
        {
            var salaries = _repo.FindAll().ToList();
            var model = _mapper.Map<List<Salary>, List<SalaryVM>>(salaries);
            return View(model);
        }

        // GET: SalaryController/Details/5
        public ActionResult Details(int id)
        {
            if (!_repo.isExist(id))
            {
                return NotFound();
            }
            var customers = _repo.FindById(id);
            var collection = _mapper.Map<SalaryVM>(customers);
            return View(collection);
        }

        // GET: SalaryController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SalaryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SalaryVM collection)
        {
            try
            {
                //TODO: Add insert logic here
                if (!ModelState.IsValid)
                {
                    return View(collection);
                }

                var salary = _mapper.Map<Salary>(collection);
                salary.DateCreated = DateTime.Now;

                var isSuccess = _repo.Create(salary);
                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something Went Wrong...");
                    return View(collection);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something Went Wrong...");
                return View(collection);
            }
        }

        // GET: SalaryController/Edit/5
        public ActionResult Edit(int id)
        {
            //checking if there is any record for that particular Id
            if (!_repo.isExist(id))
            {
                return NotFound();
            }
            var salary = _repo.FindById(id);
            var collection = _mapper.Map<SalaryVM>(salary);
            return View(collection);
        }

        // POST: SalaryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SalaryVM collection)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(collection);
                }
                var salary = _mapper.Map<Salary>(collection);
                var isSuccess = _repo.Update(salary);
                if (!isSuccess)
                {
                    ModelState.AddModelError("", "Something Went Wrong...");
                    return View(collection);
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("", "Something Went Wrong...");
                return View(collection);
            }
        }

        // GET: SalaryController/Delete/5
        public ActionResult Delete(int id)
        {
            //checking if there is any record for that particular Id
            var salary = _repo.FindById(id);
            if (salary == null)
            {
                return NotFound();
            }
            var isSuccess = _repo.Delete(salary);
            if (!isSuccess)
            {
                return View();
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: SalaryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, SalaryVM collection)
        {
            try
            {
                //TODO: Add delete logic here 
                var salary = _repo.FindById(id);
                if (salary == null)
                {
                    return NotFound();
                }
                var isSuccess = _repo.Delete(salary);
                if (!isSuccess)
                {
                    return BadRequest();
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(collection);
            }
        }
    }
}

TheThrift/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using TheThrift.Data
@inject SignInManager<Employee> SignInManager
@inject UserManager<Employee> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> TheThrift | Alajo </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TheThrift</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Clients" asp-action="Index">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Expenses" asp-action="Index">Expenses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Salary" asp-action="Index">Salary</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="LoanRequest" asp-action="Create">Apply For Loan</a>
                        </li>

                        @if (SignInManager.IsSignedIn(User))
                        {
                            //restricting menu according to the user
                            //assigning this menu to only administrator
                            if (User.IsInRole("Administrator"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Manage Loan
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="LoanTypes" asp-action="Index">Loan Types</a>
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="LoanAllocation" asp-action="Index">Loan Allocations</a>
                                        <a class="dropdown-item text-dark" asp-area="" asp-controller="LoanRequest" asp-action="Index">Loan Requests</a>
                                        <a class="dropdown-item text-dark" asp-controller="LoanAllocation" asp-action="ListEmployees">Employees</a>
                                    </div>
                                </li>
                            }
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - TheThrift | Alajo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>